### PR TITLE
Reorganized for compatibility with optional checkstyle configuration

### PR DESCRIPTION
**Pull request by w4rum**
(1) Expressions split across multiple lines
(2) Constructor split into multiple voids based on category of checks
(3) Declarations made global to work across multiple check phases (see (2))

### CODE REVIEW

**Comment by ghost** [comment]
I don't see why splitting up all the tests should help, and why did you make all Tile and Board instances globally accessible when the tests are split into smaller methods?

Also the checkstyle is not necessary for the tests.

**Comment by w4rum** [comment]
> I don't see why splitting up all the tests should help,

It removes the need to specifically disable checkstyle for the test file and allows test parameters to be read on narrow screens without horizontal scrolling.

> and why did you make all Tile and Board instances globally accessible when the tests are split into smaller methods?

That was to ensure that tests that relied on instance modifications of earlier voids were accessing the same objects. This could have been realized with function parameters but global variables make for less cluttering in this case.
I also didn't check whether any void actually realied on prior modifications, it was merely a safety procedure.

> Also the checkstyle is not necessary for the tests.

True, but why not apply the same standard consistently when it benefits readability?

**Comment by ghost** [comment]
> [..] and allows test parameters to be read on narrow screens without horizontal scrolling.

Yes, but this could have been changed in the current version by just splitting the lines as well, no need to restructure the whole class.

> True, but why not apply the same standard consistently when it benefits readability?

Not necessary because the tests is entirely seperate from the assignment, but both these changes probably come down to personal preference, so I'm not gonna complain.

> That was to ensure that tests that relied on instance modifications of earlier voids were accessing the same objects.

That is actually something you specifically **do not** want for unit tests. This is a problem we currently have in this test as well, but should address in further versions.
Many people using this test had the problem that some of their implementations accidently manipulated a Tile instance directly, not a copy. This brought the problem that later tests relying on the same objects failed, because the tested Tile was different than expected from the test.

I'm not the maintainer of this repo, so I'll leave the decision open to @DeerMichel. However big code  restructurations are generally not really appreciated.

**Comment by deermichel** [comment]
This test was meant to be simple and quick. I don't see a reason why it should have a more complex and advanced style for it likely won't be extended. Next tests gonna be based on JUnit anyhow.

**Pull request closed without merging**
