### PR TITLE
Reenable a few ignored tests with the IliasPostException-comment

### PR DESCRIPTION
**Pull request by DaDummy**
Reenable a few tests where it isn't clear which exception to expect in those cases
 -> I'd say just expect *some* RuntimeException and be done with it ;D

### CODE REVIEW

**Comment by jcgruenhage** [comment]
I'm not happy with that. One option would be to catch everything that makes sense, fail if there is no exception, and fail if there is an unexpected one.

**Comment by jcgruenhage** [comment]
I'd rather use IllegalArgumentExceptions, if anything, since all the custom exceptions provided by the framework extend that.

**Review by deermichel — DISMISSED** [review]
Please use jcgruenhage's idea (#2) if you want these tests to be reenabled.

**Comment by DaDummy** [comment]
I have implemented the requested changes

**Pull request merged**
