### PR TITLE
Add more moveTokensToBottom tests

### PR DESCRIPTION
**Pull request by FlorianPfisterer**

### CODE REVIEW

**Comment by FlorianPfisterer** [comment]
Just saw that you already created some moveTokensToBottom tests

**Comment by deermichel** [comment]
Why not awesome anymore 🐕  ?

**Comment by FlorianPfisterer** [comment]
Thought that could be misinterpreted given the fact that there are already 'moveTokensToBottom' tests ;)

**Comment by deermichel** [comment]
Nobody knows if they are awesome 🌵

**Comment by FlorianPfisterer** [comment]
At least my implementation nails them all ;)

**Pull request merged**
